export type NewsCategory = 'expedition' | 'science' | 'media' | 'press'

export const CATEGORY_COLOR: Record<NewsCategory, string> = {
  expedition: '#E03D1E',
  science:    '#1E5855',
  media:      '#C8841A',
  press:      'rgba(255,255,255,0.45)',
}

export const NEWS = [
  {
    id: 1,
    date: '2026-05-15',
    category: 'expedition' as NewsCategory,
    titleEn: 'B. Budjargal completes Gobi Desert leg — 1,200 km in 28 days',
    titleMn: 'Б.Буджаргал Говийн маршрутыг дуусгалаа — 28 хоногт 1,200 км',
    excerptEn: 'The first major segment of the expedition has been completed, crossing Mongolia\'s Gobi Desert in record time.',
    excerptMn: 'Экспедицийн эхний том маршрут болох Монголын Говийг рекорд хугацаанд туулж, амжилттай дуусгалаа.',
    href: '#',
  },
  {
    id: 2,
    date: '2026-04-28',
    category: 'science' as NewsCategory,
    titleEn: 'Research team publishes first findings on land degradation across Gobi corridor',
    titleMn: 'Судалгааны баг Говийн коридорт газрын доройтлын анхны дүнгээ нийтлэв',
    excerptEn: 'Dr. Khaulandbek\'s team released preliminary data showing accelerating desertification rates in Eastern Mongolia.',
    excerptMn: 'Д.Хауланбекийн баг Монгол Улсын зүүн хэсэгт цөлжилт хурдацтай явагдаж буйг харуулсан урьдчилсан мэдээллийг гаргалаа.',
    href: '#',
  },
  {
    id: 3,
    date: '2026-04-10',
    category: 'media' as NewsCategory,
    titleEn: 'Desert Voice documentary trailer released internationally',
    titleMn: '"Цөлийн дуу хоолой" баримтат киноны трейлер олон улсад гарлаа',
    excerptEn: 'The official trailer has been released, garnering over 2 million views in its first week across social media.',
    excerptMn: 'Ёсны трейлер гарч, эхний 7 хоногт сошиал медиад 2 саяас дээш үзэлтэй болов.',
    href: '#',
  },
  {
    id: 4,
    date: '2026-03-20',
    category: 'press' as NewsCategory,
    titleEn: 'UNCCD COP17 officially endorses Voice of the Desert initiative',
    titleMn: 'UNCCD COP17 "Цөлийн дуу хоолой" санаачилгыг албан ёсоор дэмжлээ',
    excerptEn: 'The United Nations Convention to Combat Desertification has recognized Voice of the Desert as a flagship initiative for COP17.',
    excerptMn: 'НҮБ-ын Цөлжилттэй тэмцэх конвенц "Цөлийн дуу хоолой"-г COP17-ын тэргүүлэх санаачилга болгон хүлээн зөвшөөрлөө.',
    href: '#',
  },
  {
    id: 5,
    date: '2026-03-01',
    category: 'expedition' as NewsCategory,
    titleEn: 'Route confirmed: 16,000 km across 7 nations',
    titleMn: 'Маршрут батлагдлаа: 7 улсаар дамжих 16,000 км',
    excerptEn: 'The full route connecting Mongolia, China, Kazakhstan, Kyrgyzstan, Tajikistan, Uzbekistan and Russia is officially set.',
    excerptMn: '7 улсыг холбосон бүтэн маршрут албан ёсоор батлагдлаа.',
    href: '#',
  },
  {
    id: 6,
    date: '2026-02-14',
    category: 'media' as NewsCategory,
    titleEn: 'Central Television begins live expedition coverage',
    titleMn: 'Централ Телевиз экспедицийн шууд дамжуулалтыг эхлүүллээ',
    excerptEn: 'Mongolia\'s Central Television commenced daily live coverage, reaching an estimated 15 million viewers across Eurasia.',
    excerptMn: 'Монголын Централ Телевиз өдөр тутмын шууд дамжуулалтыг эхлүүлж, Евразийн 15 сая үзэгчдэд хүрэж байна.',
    href: '#',
  },
] as const

export const TEAM = [
  {
    id: 1,
    name: 'П.Энхцэцэг',
    nameEn: 'P. Enkhtsetseg',
    roleKey: 'team.role.leader',
    descriptionMn: 'Төслийн гол санаачлагч бөгөөд удирдагч. Олон улсын хамтын ажиллагаа, стратеги, гадаад харилцааг хариуцан ажилладаг.',
    descriptionEn: 'Founder and driving force behind Voice of the Desert. Leads international partnerships, strategy, and external relations.',
    image: '/team/enkhtsetseg.jpg',
    social: { facebook: '#' },
  },
  {
    id: 2,
    name: 'Н.Солонгоцацралт',
    nameEn: 'N. Solongotatsralt',
    roleKey: 'team.role.director',
    descriptionMn: 'Гүйцэтгэх захирлын хувиар төслийн өдөр тутмын үйл ажиллагаа, санхүү, гүйцэтгэлийг хариуцан удирдана.',
    descriptionEn: 'Oversees daily operations, finance, and execution as Executive Director of the project.',
    image: '/team/solongotatsralt.jpg',
    social: { facebook: '#' },
  },
  {
    id: 3,
    name: 'Б.Батномин',
    nameEn: 'B. Batnomin',
    roleKey: 'team.role.deputy',
    descriptionMn: 'Үйл ажиллагаа хариуцсан дэд захирлын хувиар төслийн өдөр тутмын үйл ажиллагаа, гүйцэтгэлийг хариуцан удирдана.',
    descriptionEn: 'Deputy Director of Operations overseeing the day-to-day execution and operational management of the project.',
    image: '/team/batnomin.png',
    social: { facebook: '#' },
  },
  {
    id: 4,
    name: 'Б.Наминчимэд',
    nameEn: 'B. Naminchimed',
    roleKey: 'team.role.expedition',
    descriptionMn: 'Экспедицийн ахлагчийн хувиар 120 хоногийн аялалын газар дээрх гүйцэтгэл, аюулгүй байдлыг хариуцна.',
    descriptionEn: 'Expedition Leader responsible for on-ground execution and safety across the full 120-day journey.',
    image: '/team/naminchimed.png',
    social: { facebook: '#' },
  },
  {
    id: 5,
    name: 'Б.Буджаргал',
    nameEn: 'B. Budjargal',
    roleKey: 'team.role.runner',
    descriptionMn: 'Хэт холын зайн гүйлтийн дэлхийн аварга. 16,000 км замыг биечлэн туулж, Монголын санаачилгыг дэлхийд уламжлах гол хөдөлгөгч хүч.',
    descriptionEn: 'Ultra-marathon world champion. The human face of the mission — running 16,000 km to carry Mongolia\'s voice across Eurasia.',
    image: '/team/budjargal.png',
    social: { facebook: '#', instagram: '#' },
  },
  {
    id: 6,
    name: 'А.Хауланбек',
    nameEn: 'A. Khaulandbek',
    roleKey: 'team.role.scientist',
    descriptionMn: 'Газарзүй, геоэкологийн хүрээлэнгийн доктор, профессор. Маршрутын дагуух байгаль орчны судалгааг удирдан явуулна.',
    descriptionEn: 'Doctor and Professor at the Institute of Geography & Geo-ecology. Leads environmental research along the expedition route.',
    image: '/team/khaulandbek.png',
    social: { facebook: '#' },
  },
  {
    id: 7,
    name: 'Ц.Мандухай',
    nameEn: 'Ts. Mandukhai',
    roleKey: 'team.role.coordinator',
    descriptionMn: 'Ерөнхий зохицуулагчийн хувиар экспедицийн логистик, маршрут, багийн зохицуулалтыг хариуцна.',
    descriptionEn: 'General Coordinator managing expedition logistics, route planning, and team coordination.',
    image: '/team/mandukhai.png',
    social: { facebook: '#' },
  },
]

