export const TEAM = [
  {
    id: 1,
    name: 'П.Энхцэцэг',
    nameEn: 'P. Enkhtsetseg',
    roleKey: 'team.role.leader',
    descriptionMn: 'Төслийн гол санаачлагч бөгөөд удирдагч. Олон улсын хамтын ажиллагаа, стратеги, гадаад харилцааг хариуцан ажилладаг.',
    descriptionEn: 'Founder and driving force behind Voice of the Desert. Leads international partnerships, strategy, and external relations.',
    image: '/team/enkhtsetseg.jpg',
    social: { facebook: '#' },
  },
  {
    id: 2,
    name: 'Н.Солонгоцацралт',
    nameEn: 'N. Solongotatsralt',
    roleKey: 'team.role.director',
    descriptionMn: 'Гүйцэтгэх захирлын хувиар төслийн өдөр тутмын үйл ажиллагаа, санхүү, гүйцэтгэлийг хариуцан удирдана.',
    descriptionEn: 'Oversees daily operations, finance, and execution as Executive Director of the project.',
    image: '/team/solongotatsralt.jpg',
    social: { facebook: '#' },
  },
  {
    id: 3,
    name: 'Ц.Баянбилэг',
    nameEn: 'Ts. Bayanbileg',
    roleKey: 'team.role.coordinator',
    descriptionMn: 'Ерөнхий зохицуулагчийн хувиар экспедицийн логистик, маршрут, багийн зохицуулалтыг хариуцна.',
    descriptionEn: 'General Coordinator managing expedition logistics, route planning, and team coordination.',
    image: '/team/bayanbileg.jpg',
    social: { facebook: '#' },
  },
  {
    id: 4,
    name: 'Б.Наминчимэд',
    nameEn: 'B. Naminchimed',
    roleKey: 'team.role.expedition',
    descriptionMn: 'Экспедицийн ахлагчийн хувиар 120 хоногийн аялалын газар дээрх гүйцэтгэл, аюулгүй байдлыг хариуцна.',
    descriptionEn: 'Expedition Leader responsible for on-ground execution and safety across the full 120-day journey.',
    image: '/team/naminchimed.jpg',
    social: { facebook: '#' },
  },
  {
    id: 5,
    name: 'Б.Буджаргал',
    nameEn: 'B. Budjargal',
    roleKey: 'team.role.runner',
    descriptionMn: 'Хэт холын зайн гүйлтийн дэлхийн аварга. 12,000 км замыг биечлэн туулж, Монголын санаачилгыг дэлхийд уламжлах гол хөдөлгөгч хүч.',
    descriptionEn: 'Ultra-marathon world champion. The human face of the mission — running 12,000 km to carry Mongolia\'s voice across Eurasia.',
    image: '/team/budjargal.jpg',
    social: { facebook: '#', instagram: '#' },
  },
  {
    id: 6,
    name: 'А.Хауланбек',
    nameEn: 'A. Khaulandbek',
    roleKey: 'team.role.scientist',
    descriptionMn: 'Газарзүй, геоэкологийн хүрээлэнгийн доктор, профессор. Маршрутын дагуух байгаль орчны судалгааг удирдан явуулна.',
    descriptionEn: 'Doctor and Professor at the Institute of Geography & Geo-ecology. Leads environmental research along the expedition route.',
    image: '/team/haulandbek.jpg',
    social: { facebook: '#' },
  },
]

